services:

  tradeflow:

    build: .

    container_name: tradeflow-backend

    ports:
      - "5000:5000"

    volumes:
      - .:/app

    env_file:
      - .env

    restart: unless-stopped

    command: python run.py