"""Add push_subscription column to users table

Revision ID: 4bf20bcb6744
Revises: 527c6fadc048
Create Date: 2026-01-04 10:12:17.059180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '4bf20bcb6744'
down_revision = '527c6fadc048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('trade', 'analysis', 'strategy', 'system', 'alert', name='notification_type'), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_subscription', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('push_subscription')

    op.drop_table('notifications')
    # ### end Alembic commands ###
